blank_issues_enabled: false
contact_links:
  - name: Soporte interno Prevencion de Riesgos
    url: https://github.com/DonBorgiFR/Control-GPS-Transvi-a/discussions
    about: Usar Discussions para preguntas generales o soporte no bloqueante
